### ISSUE TITLE
Mark about version of FoF

### ISSUE THREAD

**Issue by willfaulds** [akeeba/todo-fof-example#17]
I think this ought to be clearly marked as depreciated and awareness drawn to the FoF3 branch being available.

For new users (those this example is targeting)

**Comment by nikosdion** [comment]
FOF 2 is still maintained since it is included in Joomla 3. Until Joomla stops including it we have to maintain it to some extent.

**Comment by willfaulds** [comment]
I understand that - I just anticipated the master branch here (FoF2) to relate to the master branch of FoF (FoF3). Its not immediately clear nor as I assumed.

Depreciated was probably the wrong choice of word.

How about clearly marking the README

"**NB this branch of todo-fof-example is built for FoF2 (which is included with Joomla3 installs). A branch is maintained for FoF3.

**Comment by nikosdion** [comment]
Switched the default branch to with-fof-3

**Comment by willfaulds** [comment]
Cheers Nik, I'm getting to grips with FOF3 - nice work ;)

Building a more featurefull branch of com_todo here too (https://github.com/willfaulds/todo-fof-example/tree/with-fof-3-extended)
